- name: Homebrewを更新する
  homebrew:
    update_homebrew: yes
  register: installed_brew
  ignore_errors: true

- name: Homebrewをインストールする
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  when: installed_brew|failed

- name: Homebrewの非公式リポジトリーを追加する
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items:
    - argon/mas
    - homebrew/cask-versions
    - homebrew/cask-fonts
    - beeftornado/rmtree

- name: masをインストールする
  homebrew:
    name: mas
    state: present

- name: App Storeのパッケージをインストールする
  shell:
    mas install {{ item }}
  with_items:
    "{{ mas_packages }}"

- name: Homebrew Caskのパッケージをインストールする
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ brew_cask_packages }}"

- name: Homebrewのパッケージをインストールする
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ brew_packages }}"

- name: anyenvをインストールする
  git:
    repo: https://github.com/riywo/anyenv.git
    dest: ~/.anyenv
