- name: Homebrewを更新する
  homebrew:
    update_homebrew: yes

- name: Homebrew Caskのパッケージをインストールする
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ brew_cask_packages }}"

- name: Homebrewのパッケージをインストールする
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ brew_packages }}"
