- name: サイズを変更する
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: int
    value: 48
  notify: killall dock

- name: 自動的に隠す
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
  notify: killall dock

- name: ウィンドウをアプリケーションアイコンに最小化する
  osx_defaults:
    domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: true
  notify: killall dock
