- name: 隠しファイルを表示する
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
  notify: killall finder

- name: 常にリストビューにする
  osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: clmv
  notify: killall finder

- name: ホームから開くようにする
  osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: PfLo
  notify: killall finder

- name: ホームから開くようにする
  osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    type: string
    value: file://${HOME}/
  notify: killall finder

- name: パスバーの階層表示をホームから開始する
  osx_defaults:
    domain: com.apple.finder
    key: PathBarRootAtHome
    type: bool
    value: true
  notify: killall finder

- name: クイックルックのテキストをコピー可能にする
  osx_defaults:
    domain: com.apple.finder
    key: QLEnableTextSelection
    type: bool
    value: true
  notify: killall finder

- name: 他のアプリケーションに切り替えたらクイックルックを隠す
  osx_defaults:
    domain: com.apple.finder
    key: QLHidePanelOnDeactivate
    type: bool
    value: true
  notify: killall finder

- name: ファイル拡張子変更時の警告を無効にする
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false
  notify: killall finder

- name: デスクトップを無効にする
  osx_defaults:
    domain: com.apple.finder
    key: CreateDesktop
    type: bool
    value: false
  notify: killall finder

- name: アニメーションを無効にする
  osx_defaults:
    domain: com.apple.finder
    key: DisableAllAnimations
    type: bool
    value: true
  notify: killall finder
